[package]
name = "artnet-client"
version = "0.1.0"
edition = "2024"

[package.metadata.cargo-matrix]
[[package.metadata.cargo-matrix.channel]]
name = "esp32c5"
always_include = ["producer", "receiver", "esp32c5"]
always_deny = ["esp32c6"]
mutually_exclusive = [["io-udp", "io-wpan"], ["esp32c5", "esp32c6"]]

[[package.metadata.cargo-matrix.channel]]
name = "esp32c6"
always_include = ["producer", "receiver", "esp32c6"]
always_deny = ["esp32c5"]
mutually_exclusive = [["io-udp", "io-wpan"], ["esp32c5", "esp32c6"]]

[[package.metadata.cargo-matrix.channel]]
name = "default"
always_deny = ["io-wpan", "esp32c5", "esp32c6"]

[dependencies]
async-channel = { version = "2.5", default-features = false }
async-trait = "0.1"
bytes = { version = "1.11", default-features = false }
cfg-if = "1.0"
derive_more = { version = "2.1", default-features = false, features = ["full"] }
derive-new = { version = "0.7", default-features = false }
thiserror = { version = "2.0", default-features = false }
tiny-artnet = { path = "../tiny-artnet/", version = "0.1" }

# embassy-executor = { version = "0.10", features = ["defmt"] }
embassy-futures = { version = "0.1", features = ["defmt"] }

tracing = {
  version = "0.1.44",
  default-features = false,
  features = ["attributes"]
}
# tracing-defmt = { path = "../tracing-defmt/", version = "*" }

# --- UDP ---

edge-nal-embassy = {
  version = "0.8",
  features = ["proto-ipv4", "udp"],
  optional = true
}
edge-net = {
  version = "0.13",
  features = ["defmt", "edge-nal-embassy", "embassy"],
  optional = true
}
embassy-net = {
  version = "0.8",
  features = ["alloc", "defmt", "tcp", "udp"],
  optional = true
}

# --- WPAN ---

esp-hal = { version = "1.1", features = ["unstable"], optional = true }
esp-radio = {
  version = "0.18",
  features = ["ieee802154", "unstable"],
  optional = true
}
ieee802154 = { version = "0.6", optional = true }

# --- SERDE ---

serde = { version = "1.0", features = ["alloc", "derive"], optional = true , default-features = false }

[dev-dependencies]
anyhow = "1.0"
bevy_color = "0.18"
derive_more = { version = "2.1", features = ["deref", "deref_mut", "from"] }
edge-nal-std = "0.6"
iocraft = "0.8"
rand = "0.10"
smol = "2.0"
smol-macros = "0.1"
tracing-subscriber = { version = "0.3.23", features = ["env-filter", "fmt"] }

[features]
default = ["producer", "receiver"]
esp32c5 = ["esp-hal/esp32c5", "esp-radio/esp32c5"]
esp32c6 = ["esp-hal/esp32c6", "esp-radio/esp32c6"]
io-udp = ["dep:edge-nal-embassy", "dep:edge-net", "dep:embassy-net"]
io-wpan = [
  "dep:esp-hal",
  "dep:esp-radio",
  "dep:ieee802154",
]
producer = []
receiver = []
serde = ["bytes/serde", "dep:serde"]

[profile.release]
opt-level = 3
debug = false
strip = true
lto = "thin"
